//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MolecularWeightCalculator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MolecularWeightCalculator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number,name,symbol,atomic_weight
        ///1,Hydrogen,H,1.008
        ///2,Helium,He,4.0026022
        ///3,Lithium,Li,6.94
        ///4,Beryllium,Be,9.01218315
        ///5,Boron,B,10.81
        ///6,Carbon,C,12.011
        ///7,Nitrogen,N,14.007
        ///8,Oxygen,O,15.999
        ///9,Fluorine,F,18.99840316
        ///10,Neon,Ne,20.17976
        ///11,Sodium,Na,22.98976928
        ///12,Magnesium,Mg,24.305
        ///13,Aluminum,Al,26.98153857
        ///14,Silicon,Si,28.085
        ///15,Phosphorus,P,30.973762
        ///16,Sulfur,S,32.06
        ///17,Chlorine,Cl,35.45
        ///18,Argon,Ar,39.9481
        ///19,Potassium,K,39.09831
        ///20,Calcium,Ca,40.0784
        ///21,Scandium,Sc,44.9559085
        ///22 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string periodic_table {
            get {
                return ResourceManager.GetString("periodic_table", resourceCulture);
            }
        }
    }
}
